language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
branches:
  only:
    - master
before_install:
  - sudo apt-get -qq update
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run build
  - npm run semantic-release
